// The 193 UN member states with ISO 3166-1 alpha-3 codes and capitals. This is
// the *candidate* seed only — every capital here is cross-checked against
// Wikidata (P36) by build-countries.ts and independently re-verified before it
// ships. `note` flags the genuinely non-obvious cases (split capitals, recent
// moves, contested status) so reviewers know they were a deliberate choice, not
// a typo. Order is alphabetical for a clean, reviewable diff.

export type SeedCountry = {
  country: string
  iso3: string
  capital: string
  note?: string
}

export const UN_MEMBERS: SeedCountry[] = [
  { country: 'Afghanistan', iso3: 'AFG', capital: 'Kabul' },
  { country: 'Albania', iso3: 'ALB', capital: 'Tirana' },
  { country: 'Algeria', iso3: 'DZA', capital: 'Algiers' },
  { country: 'Andorra', iso3: 'AND', capital: 'Andorra la Vella' },
  { country: 'Angola', iso3: 'AGO', capital: 'Luanda' },
  { country: 'Antigua and Barbuda', iso3: 'ATG', capital: "Saint John's" },
  { country: 'Argentina', iso3: 'ARG', capital: 'Buenos Aires' },
  { country: 'Armenia', iso3: 'ARM', capital: 'Yerevan' },
  { country: 'Australia', iso3: 'AUS', capital: 'Canberra' },
  { country: 'Austria', iso3: 'AUT', capital: 'Vienna' },
  { country: 'Azerbaijan', iso3: 'AZE', capital: 'Baku' },
  { country: 'Bahamas', iso3: 'BHS', capital: 'Nassau' },
  { country: 'Bahrain', iso3: 'BHR', capital: 'Manama' },
  { country: 'Bangladesh', iso3: 'BGD', capital: 'Dhaka' },
  { country: 'Barbados', iso3: 'BRB', capital: 'Bridgetown' },
  { country: 'Belarus', iso3: 'BLR', capital: 'Minsk' },
  { country: 'Belgium', iso3: 'BEL', capital: 'Brussels' },
  { country: 'Belize', iso3: 'BLZ', capital: 'Belmopan' },
  {
    country: 'Benin',
    iso3: 'BEN',
    capital: 'Porto-Novo',
    note: 'Porto-Novo is the official capital; Cotonou is the seat of government.'
  },
  { country: 'Bhutan', iso3: 'BTN', capital: 'Thimphu' },
  {
    country: 'Bolivia',
    iso3: 'BOL',
    capital: 'Sucre',
    note: 'Sucre is the constitutional capital; La Paz is the seat of government.'
  },
  { country: 'Bosnia and Herzegovina', iso3: 'BIH', capital: 'Sarajevo' },
  { country: 'Botswana', iso3: 'BWA', capital: 'Gaborone' },
  { country: 'Brazil', iso3: 'BRA', capital: 'Brasília' },
  { country: 'Brunei', iso3: 'BRN', capital: 'Bandar Seri Begawan' },
  { country: 'Bulgaria', iso3: 'BGR', capital: 'Sofia' },
  { country: 'Burkina Faso', iso3: 'BFA', capital: 'Ouagadougou' },
  {
    country: 'Burundi',
    iso3: 'BDI',
    capital: 'Gitega',
    note: 'Gitega became the political capital in 2019; Bujumbura remains the economic centre.'
  },
  { country: 'Cabo Verde', iso3: 'CPV', capital: 'Praia' },
  { country: 'Cambodia', iso3: 'KHM', capital: 'Phnom Penh' },
  { country: 'Cameroon', iso3: 'CMR', capital: 'Yaoundé' },
  { country: 'Canada', iso3: 'CAN', capital: 'Ottawa' },
  { country: 'Central African Republic', iso3: 'CAF', capital: 'Bangui' },
  { country: 'Chad', iso3: 'TCD', capital: "N'Djamena" },
  { country: 'Chile', iso3: 'CHL', capital: 'Santiago' },
  { country: 'China', iso3: 'CHN', capital: 'Beijing' },
  { country: 'Colombia', iso3: 'COL', capital: 'Bogotá' },
  { country: 'Comoros', iso3: 'COM', capital: 'Moroni' },
  { country: 'Republic of the Congo', iso3: 'COG', capital: 'Brazzaville' },
  { country: 'Democratic Republic of the Congo', iso3: 'COD', capital: 'Kinshasa' },
  { country: 'Costa Rica', iso3: 'CRI', capital: 'San José' },
  {
    country: "Côte d'Ivoire",
    iso3: 'CIV',
    capital: 'Yamoussoukro',
    note: 'Yamoussoukro is the official capital; Abidjan is the seat of government.'
  },
  { country: 'Croatia', iso3: 'HRV', capital: 'Zagreb' },
  { country: 'Cuba', iso3: 'CUB', capital: 'Havana' },
  { country: 'Cyprus', iso3: 'CYP', capital: 'Nicosia' },
  { country: 'Czechia', iso3: 'CZE', capital: 'Prague' },
  { country: 'Denmark', iso3: 'DNK', capital: 'Copenhagen' },
  { country: 'Djibouti', iso3: 'DJI', capital: 'Djibouti' },
  { country: 'Dominica', iso3: 'DMA', capital: 'Roseau' },
  { country: 'Dominican Republic', iso3: 'DOM', capital: 'Santo Domingo' },
  { country: 'Ecuador', iso3: 'ECU', capital: 'Quito' },
  { country: 'Egypt', iso3: 'EGY', capital: 'Cairo' },
  { country: 'El Salvador', iso3: 'SLV', capital: 'San Salvador' },
  { country: 'Equatorial Guinea', iso3: 'GNQ', capital: 'Malabo' },
  { country: 'Eritrea', iso3: 'ERI', capital: 'Asmara' },
  { country: 'Estonia', iso3: 'EST', capital: 'Tallinn' },
  {
    country: 'Eswatini',
    iso3: 'SWZ',
    capital: 'Mbabane',
    note: 'Mbabane is the administrative capital; Lobamba is the royal and legislative capital.'
  },
  { country: 'Ethiopia', iso3: 'ETH', capital: 'Addis Ababa' },
  { country: 'Fiji', iso3: 'FJI', capital: 'Suva' },
  { country: 'Finland', iso3: 'FIN', capital: 'Helsinki' },
  { country: 'France', iso3: 'FRA', capital: 'Paris' },
  { country: 'Gabon', iso3: 'GAB', capital: 'Libreville' },
  { country: 'Gambia', iso3: 'GMB', capital: 'Banjul' },
  { country: 'Georgia', iso3: 'GEO', capital: 'Tbilisi' },
  { country: 'Germany', iso3: 'DEU', capital: 'Berlin' },
  { country: 'Ghana', iso3: 'GHA', capital: 'Accra' },
  { country: 'Greece', iso3: 'GRC', capital: 'Athens' },
  { country: 'Grenada', iso3: 'GRD', capital: "Saint George's" },
  { country: 'Guatemala', iso3: 'GTM', capital: 'Guatemala City' },
  { country: 'Guinea', iso3: 'GIN', capital: 'Conakry' },
  { country: 'Guinea-Bissau', iso3: 'GNB', capital: 'Bissau' },
  { country: 'Guyana', iso3: 'GUY', capital: 'Georgetown' },
  { country: 'Haiti', iso3: 'HTI', capital: 'Port-au-Prince' },
  { country: 'Honduras', iso3: 'HND', capital: 'Tegucigalpa' },
  { country: 'Hungary', iso3: 'HUN', capital: 'Budapest' },
  { country: 'Iceland', iso3: 'ISL', capital: 'Reykjavík' },
  { country: 'India', iso3: 'IND', capital: 'New Delhi' },
  {
    country: 'Indonesia',
    iso3: 'IDN',
    capital: 'Jakarta',
    note: 'Jakarta remains the capital; a planned move to Nusantara is still in transition.'
  },
  { country: 'Iran', iso3: 'IRN', capital: 'Tehran' },
  { country: 'Iraq', iso3: 'IRQ', capital: 'Baghdad' },
  { country: 'Ireland', iso3: 'IRL', capital: 'Dublin' },
  {
    country: 'Israel',
    iso3: 'ISR',
    capital: 'Jerusalem',
    note: 'Jerusalem is the seat of government; its status is contested internationally.'
  },
  { country: 'Italy', iso3: 'ITA', capital: 'Rome' },
  { country: 'Jamaica', iso3: 'JAM', capital: 'Kingston' },
  { country: 'Japan', iso3: 'JPN', capital: 'Tokyo' },
  { country: 'Jordan', iso3: 'JOR', capital: 'Amman' },
  {
    country: 'Kazakhstan',
    iso3: 'KAZ',
    capital: 'Astana',
    note: 'Renamed Nur-Sultan 2019–2022, then reverted to Astana.'
  },
  { country: 'Kenya', iso3: 'KEN', capital: 'Nairobi' },
  {
    country: 'Kiribati',
    iso3: 'KIR',
    capital: 'South Tarawa',
    note: 'Government sits on South Tarawa atoll; sometimes given as Tarawa.'
  },
  { country: 'Kuwait', iso3: 'KWT', capital: 'Kuwait City' },
  { country: 'Kyrgyzstan', iso3: 'KGZ', capital: 'Bishkek' },
  { country: 'Laos', iso3: 'LAO', capital: 'Vientiane' },
  { country: 'Latvia', iso3: 'LVA', capital: 'Riga' },
  { country: 'Lebanon', iso3: 'LBN', capital: 'Beirut' },
  { country: 'Lesotho', iso3: 'LSO', capital: 'Maseru' },
  { country: 'Liberia', iso3: 'LBR', capital: 'Monrovia' },
  { country: 'Libya', iso3: 'LBY', capital: 'Tripoli' },
  { country: 'Liechtenstein', iso3: 'LIE', capital: 'Vaduz' },
  { country: 'Lithuania', iso3: 'LTU', capital: 'Vilnius' },
  { country: 'Luxembourg', iso3: 'LUX', capital: 'Luxembourg' },
  { country: 'Madagascar', iso3: 'MDG', capital: 'Antananarivo' },
  { country: 'Malawi', iso3: 'MWI', capital: 'Lilongwe' },
  {
    country: 'Malaysia',
    iso3: 'MYS',
    capital: 'Kuala Lumpur',
    note: 'Kuala Lumpur is the official capital; Putrajaya is the administrative centre.'
  },
  { country: 'Maldives', iso3: 'MDV', capital: 'Malé' },
  { country: 'Mali', iso3: 'MLI', capital: 'Bamako' },
  { country: 'Malta', iso3: 'MLT', capital: 'Valletta' },
  { country: 'Marshall Islands', iso3: 'MHL', capital: 'Majuro' },
  { country: 'Mauritania', iso3: 'MRT', capital: 'Nouakchott' },
  { country: 'Mauritius', iso3: 'MUS', capital: 'Port Louis' },
  { country: 'Mexico', iso3: 'MEX', capital: 'Mexico City' },
  { country: 'Micronesia', iso3: 'FSM', capital: 'Palikir' },
  { country: 'Moldova', iso3: 'MDA', capital: 'Chișinău' },
  { country: 'Monaco', iso3: 'MCO', capital: 'Monaco' },
  { country: 'Mongolia', iso3: 'MNG', capital: 'Ulaanbaatar' },
  { country: 'Montenegro', iso3: 'MNE', capital: 'Podgorica' },
  { country: 'Morocco', iso3: 'MAR', capital: 'Rabat' },
  { country: 'Mozambique', iso3: 'MOZ', capital: 'Maputo' },
  { country: 'Myanmar', iso3: 'MMR', capital: 'Naypyidaw' },
  { country: 'Namibia', iso3: 'NAM', capital: 'Windhoek' },
  {
    country: 'Nauru',
    iso3: 'NRU',
    capital: 'Yaren',
    note: 'Nauru has no official capital; Yaren is the de facto seat of government.'
  },
  { country: 'Nepal', iso3: 'NPL', capital: 'Kathmandu' },
  {
    country: 'Netherlands',
    iso3: 'NLD',
    capital: 'Amsterdam',
    note: 'Amsterdam is the constitutional capital; The Hague is the seat of government.'
  },
  { country: 'New Zealand', iso3: 'NZL', capital: 'Wellington' },
  { country: 'Nicaragua', iso3: 'NIC', capital: 'Managua' },
  { country: 'Niger', iso3: 'NER', capital: 'Niamey' },
  { country: 'Nigeria', iso3: 'NGA', capital: 'Abuja' },
  { country: 'North Korea', iso3: 'PRK', capital: 'Pyongyang' },
  { country: 'North Macedonia', iso3: 'MKD', capital: 'Skopje' },
  { country: 'Norway', iso3: 'NOR', capital: 'Oslo' },
  { country: 'Oman', iso3: 'OMN', capital: 'Muscat' },
  { country: 'Pakistan', iso3: 'PAK', capital: 'Islamabad' },
  { country: 'Palau', iso3: 'PLW', capital: 'Ngerulmud' },
  { country: 'Panama', iso3: 'PAN', capital: 'Panama City' },
  { country: 'Papua New Guinea', iso3: 'PNG', capital: 'Port Moresby' },
  { country: 'Paraguay', iso3: 'PRY', capital: 'Asunción' },
  { country: 'Peru', iso3: 'PER', capital: 'Lima' },
  { country: 'Philippines', iso3: 'PHL', capital: 'Manila' },
  { country: 'Poland', iso3: 'POL', capital: 'Warsaw' },
  { country: 'Portugal', iso3: 'PRT', capital: 'Lisbon' },
  { country: 'Qatar', iso3: 'QAT', capital: 'Doha' },
  { country: 'Romania', iso3: 'ROU', capital: 'Bucharest' },
  { country: 'Russia', iso3: 'RUS', capital: 'Moscow' },
  { country: 'Rwanda', iso3: 'RWA', capital: 'Kigali' },
  { country: 'Saint Kitts and Nevis', iso3: 'KNA', capital: 'Basseterre' },
  { country: 'Saint Lucia', iso3: 'LCA', capital: 'Castries' },
  { country: 'Saint Vincent and the Grenadines', iso3: 'VCT', capital: 'Kingstown' },
  { country: 'Samoa', iso3: 'WSM', capital: 'Apia' },
  { country: 'San Marino', iso3: 'SMR', capital: 'San Marino' },
  { country: 'Sao Tome and Principe', iso3: 'STP', capital: 'São Tomé' },
  { country: 'Saudi Arabia', iso3: 'SAU', capital: 'Riyadh' },
  { country: 'Senegal', iso3: 'SEN', capital: 'Dakar' },
  { country: 'Serbia', iso3: 'SRB', capital: 'Belgrade' },
  { country: 'Seychelles', iso3: 'SYC', capital: 'Victoria' },
  { country: 'Sierra Leone', iso3: 'SLE', capital: 'Freetown' },
  { country: 'Singapore', iso3: 'SGP', capital: 'Singapore' },
  { country: 'Slovakia', iso3: 'SVK', capital: 'Bratislava' },
  { country: 'Slovenia', iso3: 'SVN', capital: 'Ljubljana' },
  { country: 'Solomon Islands', iso3: 'SLB', capital: 'Honiara' },
  { country: 'Somalia', iso3: 'SOM', capital: 'Mogadishu' },
  {
    country: 'South Africa',
    iso3: 'ZAF',
    capital: 'Pretoria',
    note: 'Pretoria is the administrative capital; Cape Town is legislative and Bloemfontein judicial.'
  },
  { country: 'South Korea', iso3: 'KOR', capital: 'Seoul' },
  { country: 'South Sudan', iso3: 'SSD', capital: 'Juba' },
  { country: 'Spain', iso3: 'ESP', capital: 'Madrid' },
  {
    country: 'Sri Lanka',
    iso3: 'LKA',
    capital: 'Sri Jayawardenepura Kotte',
    note: 'Administrative capital; Colombo is the commercial capital and largest city.'
  },
  { country: 'Sudan', iso3: 'SDN', capital: 'Khartoum' },
  { country: 'Suriname', iso3: 'SUR', capital: 'Paramaribo' },
  { country: 'Sweden', iso3: 'SWE', capital: 'Stockholm' },
  { country: 'Switzerland', iso3: 'CHE', capital: 'Bern' },
  { country: 'Syria', iso3: 'SYR', capital: 'Damascus' },
  { country: 'Tajikistan', iso3: 'TJK', capital: 'Dushanbe' },
  {
    country: 'Tanzania',
    iso3: 'TZA',
    capital: 'Dodoma',
    note: 'Dodoma is the official capital; Dar es Salaam is the largest city.'
  },
  { country: 'Thailand', iso3: 'THA', capital: 'Bangkok' },
  { country: 'Timor-Leste', iso3: 'TLS', capital: 'Dili' },
  { country: 'Togo', iso3: 'TGO', capital: 'Lomé' },
  { country: 'Tonga', iso3: 'TON', capital: "Nuku'alofa" },
  { country: 'Trinidad and Tobago', iso3: 'TTO', capital: 'Port of Spain' },
  { country: 'Tunisia', iso3: 'TUN', capital: 'Tunis' },
  { country: 'Turkey', iso3: 'TUR', capital: 'Ankara' },
  { country: 'Turkmenistan', iso3: 'TKM', capital: 'Ashgabat' },
  { country: 'Tuvalu', iso3: 'TUV', capital: 'Funafuti' },
  { country: 'Uganda', iso3: 'UGA', capital: 'Kampala' },
  { country: 'Ukraine', iso3: 'UKR', capital: 'Kyiv' },
  { country: 'United Arab Emirates', iso3: 'ARE', capital: 'Abu Dhabi' },
  { country: 'United Kingdom', iso3: 'GBR', capital: 'London' },
  { country: 'United States', iso3: 'USA', capital: 'Washington, D.C.' },
  { country: 'Uruguay', iso3: 'URY', capital: 'Montevideo' },
  { country: 'Uzbekistan', iso3: 'UZB', capital: 'Tashkent' },
  { country: 'Vanuatu', iso3: 'VUT', capital: 'Port Vila' },
  { country: 'Venezuela', iso3: 'VEN', capital: 'Caracas' },
  { country: 'Vietnam', iso3: 'VNM', capital: 'Hanoi' },
  { country: 'Yemen', iso3: 'YEM', capital: "Sana'a" },
  { country: 'Zambia', iso3: 'ZMB', capital: 'Lusaka' },
  { country: 'Zimbabwe', iso3: 'ZWE', capital: 'Harare' }
]
